### ISSUE TITLE
example fails with the following error

### ISSUE THREAD

**Issue by 11011-binary** [PureAsbestos/KivEnt-Wheels-Win64-Py3.6#2]
Traceback (most recent call last):
   File "C:\Users\win10\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Users\win10\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Users\win10\kvy\kivent\examples\9_twinkling_stars\main.py", line 6, in <module>
     import kivent_core
   File "C:\Users\win10\AppData\Local\Programs\Python\Python36\lib\site-packages\kivent_core\__init__.py", line 8, in <module>
     from kivent_core import rendering
   File "C:\Users\win10\AppData\Local\Programs\Python\Python36\lib\site-packages\kivent_core\rendering\__init__.py", line 1, in <module>
     from kivent_core.rendering import vertex_format
   File "_event.pxd", line 12, in init kivent_core.rendering.vertex_format
 ValueError: kivy._event.EventDispatcher has the wrong size, try recompiling. Expected 80, got 72

**Comment by 11011-binary** [comment]
using the latest kivy dev build 2.0

**Comment by PureAsbestos** [comment]
I believe this is a problem with kivy, rather than kivent (most likely the version of kivy you are using is incompatible)

**Comment by PureAsbestos** [comment]
You should try an older version of kivy (1.10.0 is what it was originally tested with)
